#!/usr/bin/env node
/**
 * Build an independent ground truth for local recall.
 *
 * WHY THIS EXISTS
 * The shadow log scores local recall against mem0's own top-10. That measures
 * imitation: a local retriever that answers *better* than mem0 scores *worse*,
 * and mem0's own misses are inherited as truth. Every ship/no-ship decision about
 * the local path needs a gold set: queries carrying independent relevance
 * judged on the query and the memory text alone, with no reference to any
 * retriever's ranking.
 *
 * TWO STAGES
 *   stage 1 (offline, no credentials): sample queries and build a retriever-
 *     neutral candidate pool. Writes gold-candidates.json.
 *   stage 2 (needs an LLM key): judge each query against its pool and write
 *     gold.json.
 *
 * The candidate pool is the UNION of every ranking recorded in the shadow log
 * (remote, legacy local, dense, BM25, fusion). A union is what makes the gold set
 * fair to every scorer: if the pool were built from one retriever's output, a
 * different retriever's correct answer could never be judged relevant, and that
 * scorer would be penalised for being right where the pool builder was wrong.
 *
 * Usage:
 *   node scripts/build-gold.mjs                      # stage 1
 *   node scripts/build-gold.mjs --out /tmp/g.json    # custom output
 *   node scripts/build-gold.mjs --sample 80          # query count (default 80)
 *   node scripts/build-gold.mjs --seed 7             # sampling seed
 *   node scripts/build-gold.mjs --report             # pool statistics only
 */

import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const HOME = homedir();
const argv = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = argv.indexOf(`--${name}`);
  if (i === -1) return fallback;
  const next = argv[i + 1];
  return next === undefined || next.startsWith("--") ? true : next;
};

const STORE_PATH = flag("store", process.env.MEM0_CACHE_PATH ?? join(HOME, ".pi/agent/mem0-cache.json"));
const SHADOW_PATH = flag("shadow", process.env.MEM0_CACHE_SHADOW_PATH ?? join(HOME, ".pi/agent/mem0-shadow.jsonl"));
const OUT = flag("out", join(process.cwd(), "gold-candidates.json"));
const SAMPLE = Number(flag("sample", 80));
const SEED = Number(flag("seed", 20260927));
const REPORT_ONLY = Boolean(flag("report", false));
const MIN_QUERY_CHARS = Number(flag("min-chars", 8));
const MAX_QUERY_CHARS = Number(flag("max-chars", 400));
const PER_BUCKET_MAX = Number(flag("per-bucket", 12));

// ---------------------------------------------------------------------------
// Deterministic sampling

/** mulberry32: small, fast, and reproducible from an integer seed so a gold set
 *  can be regenerated byte-identically for a later ablation run. */
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffled(items, seed) {
  const out = [...items];
  const rand = rng(seed);
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

// ---------------------------------------------------------------------------
// Query-shape classification

/**
 * Shapes a query by what a retriever can extract from it. This matters because
 * the four channels fail on different shapes: BM25 has nothing to match on a
 * bare "继续", dense can bridge a paraphrase, and neither helps when the query
 * names nothing the memory mentions. Sampling across shapes keeps the gold set
 * representative of real traffic; scoring against an average over one shape is
 * how a channel gets a reputation it does not deserve.
 */
function shapeOf(query) {
  const q = query.trim();
  const cjk = (q.match(/[\u4e00-\u9fff]/g) ?? []).length;
  const latin = (q.match(/[a-zA-Z0-9]+/g) ?? []).length;
  if (q.length <= 12 && latin <= 1) return "terse-cjk";
  if (cjk > 0 && latin > 0) return "mixed";
  if (cjk > 0) return "cjk-only";
  return "latin";
}

/** Noise that should never enter a gold set: terminal dumps, paths, and
 *  agent-internal control strings are not memory queries. */
function isNoise(query) {
  const q = query.trim();
  if (q.length < MIN_QUERY_CHARS || q.length > MAX_QUERY_CHARS) return true;
  // Strip wrapping quotes first: a quoted path is still a path.
  const bare = q.replace(/^['"`]|['"`]$/g, "").trim();
  // A lone path, with or without a file extension, reads as a paste.
  if (/^(\/|[A-Za-z]:\\|~\/)/.test(bare) && !/\s/.test(bare)) return true;
  // A path that is most of the string, even with trailing words.
  if (/^(\/|[A-Za-z]:\\|~\/)\S*\.[A-Za-z0-9]{1,5}$/.test(bare)) return true;
  if (/waveterm_paste|\/var\/folders/.test(q)) return true;
  // Slash-commands and agent control strings.
  if (/^\/\S+$/.test(bare)) return true;
  if (/^[\s\p{P}\p{S}]+$/u.test(q)) return true;
  // Raw tool/JSON payloads leaked into a query field.
  if (/^[{[]/.test(bare) && /[}\]]$/.test(bare)) return true;
  // Diagnostics and log excerpts: a bracketed tag or a file path anywhere in a
  // long string means the user pasted output, and no memory answers a paste.
  if (/^\[/.test(bare) && /[~/\/]\.?\w+\//.test(bare)) return true;
  if (/\b(error|warning|traceback|stack trace|enclosing|at line \d+)\b/i.test(q) && /[~/\/]/.test(q)) return true;
  // Config/launch dumps: a leading step marker followed by 4+ numbered items.
  if (/^\s*\d+\./.test(q) && (q.match(/\d+\./g) ?? []).length >= 4) return true;
  // Subagent dispatch prompts. A routed task is not what a retrieval system is
  // asked to answer; including them would let lane instructions dominate the set.
  if (/^Task:\s/.test(bare)) return true;
  if (/^\s*You are (an?|the)\b.*(lane|agent|researcher)/i.test(bare)) return true;
  // Scratch probes that leaked into traffic (smoke tests, connectivity checks).
  if (/^Reply with exactly\b/i.test(bare)) return true;
  return false;
}

// ---------------------------------------------------------------------------
// Load

const store = JSON.parse(readFileSync(STORE_PATH, "utf8"));
const live = new Map();
for (const m of Object.values(store.memories ?? {})) {
  if (!m || m.deleted) continue;
  live.set(m.id, m);
}

const entries = [];
for (const line of readFileSync(SHADOW_PATH, "utf8").split("\n")) {
  if (!line.trim()) continue;
  try {
    entries.push(JSON.parse(line));
  } catch {
    /* torn final line from a concurrent append */
  }
}

// ---------------------------------------------------------------------------
// Pool construction

/** Union every recorded ranking, keeping only ids the mirror still holds.
 *  A judged-relevant id that is absent from the corpus can never be retrieved,
 *  so counting it would lower every scorer's score identically and add noise
 *  without adding signal. */
function poolFor(entry) {
  const ids = new Set();
  for (const key of ["remote", "local", "localVec", "localBm25", "localFusion"]) {
    const list = entry[key];
    if (!Array.isArray(list)) continue;
    for (const hit of list) {
      const id = typeof hit === "string" ? hit : hit?.id;
      if (typeof id === "string" && live.has(id)) ids.add(id);
    }
  }
  return [...ids].sort();
}

const candidates = [];
const seenQueries = new Set();
for (const e of entries) {
  if (e.mode !== "remote") continue;
  const query = (e.query ?? "").trim();
  if (!query || isNoise(query)) continue;
  // One row per distinct query: a repeated query adds pool overlap and no signal.
  const dedupeKey = query.toLowerCase();
  if (seenQueries.has(dedupeKey)) continue;
  const pool = poolFor(e);
  if (pool.length === 0) continue;
  seenQueries.add(dedupeKey);
  candidates.push({
    query,
    shape: shapeOf(query),
    queryChars: query.length,
    // Scope of the original request: the pool was formed under it, so judging
    // must see the same scope or it will call a cross-project memory relevant.
    scope: e.filters ?? null,
    pool,
    /** Retriever rankings, kept for a later "who found it first" analysis.
     *  These are NOT the ground truth and must never be scored as such. */
    rankings: {
      ...(Array.isArray(e.remote) ? { remote: e.remote.map((h) => h?.id ?? h).filter((id) => live.has(id)) } : {}),
      ...(Array.isArray(e.local) ? { local: e.local.map((h) => h?.id ?? h).filter((id) => live.has(id)) } : {}),
      ...(Array.isArray(e.localBm25) ? { bm25: e.localBm25.map((h) => h?.id ?? h).filter((id) => live.has(id)) } : {}),
      ...(Array.isArray(e.localFusion) ? { fusion: e.localFusion.filter((id) => live.has(id)) } : {}),
      ...(Array.isArray(e.localVec) ? { dense: e.localVec.map((h) => h?.id ?? h).filter((id) => live.has(id)) } : {}),
    },
  });
}

// ---------------------------------------------------------------------------
// Stratified sample

const buckets = new Map();
for (const c of candidates) {
  if (!buckets.has(c.shape)) buckets.set(c.shape, []);
  buckets.get(c.shape).push(c);
}

const picked = [];
const perShape = Math.max(1, Math.ceil(SAMPLE / Math.max(1, buckets.size)));
for (const [shape, rows] of [...buckets.entries()].sort()) {
  const ordered = shuffled(rows, SEED + shape.length);
  picked.push(...ordered.slice(0, Math.min(perShape, PER_BUCKET_MAX, rows.length)));
}
const sample = shuffled(picked, SEED).slice(0, SAMPLE).sort((a, b) => a.query.localeCompare(b.query));

// ---------------------------------------------------------------------------
// Report

const shapeCounts = {};
for (const c of candidates) shapeCounts[c.shape] = (shapeCounts[c.shape] ?? 0) + 1;
const poolSizes = candidates.map((c) => c.pool.length).sort((a, b) => a - b);
const median = poolSizes.length ? poolSizes[Math.floor(poolSizes.length / 2)] : 0;

/** How often each retriever's top-10 already covers the whole pool: a high value
 *  means the pool is dominated by that retriever and the gold set will be biased
 *  toward it unless the judge is strict. */
const coverage = {};
for (const c of candidates) {
  for (const [name, ranked] of Object.entries(c.rankings)) {
    if (ranked.length === 0) continue;
    const share = c.pool.length ? ranked.length / c.pool.length : 0;
    (coverage[name] ??= []).push(share);
  }
}
const mean = (xs) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0);

console.log(`store:    ${STORE_PATH} (${live.size} live memories)`);
console.log(`shadow:   ${SHADOW_PATH} (${entries.length} entries)`);
console.log(`eligible queries: ${candidates.length}`);
console.log(`shapes:   ${Object.entries(shapeCounts).map(([k, v]) => `${k}=${v}`).join("  ")}`);
console.log(`pool size: median ${median}, min ${poolSizes[0] ?? 0}, max ${poolSizes.at(-1) ?? 0}`);
console.log("pool domination by each retriever's own list (mean share of pool):");
for (const [name, shares] of Object.entries(coverage).sort()) {
  console.log(`  ${name.padEnd(8)} ${(mean(shares) * 100).toFixed(1)}%  (n=${shares.length})`);
}
const sampleShapes = {};
for (const c of sample) sampleShapes[c.shape] = (sampleShapes[c.shape] ?? 0) + 1;
console.log(`sample:   ${sample.length} queries — ${Object.entries(sampleShapes).map(([k, v]) => `${k}=${v}`).join("  ")}`);

if (REPORT_ONLY) process.exit(0);

// ---------------------------------------------------------------------------
// Write

const out = {
  generated_at: new Date().toISOString(),
  seed: SEED,
  store_path: STORE_PATH,
  shadow_path: SHADOW_PATH,
  /**
   * Judging instructions, embedded so the judge step cannot drift from the
   * sampling rules. Graded relevance is what lets the ablation distinguish
   * "found the right memory" from "found a related one".
   */
  judge_protocol: {
    scale: { 2: "directly answers the query", 1: "related and plausibly useful", 0: "not relevant" },
    rules: [
      "Judge each memory on the query text and the memory text alone.",
      "Ignore which retriever returned it and at what rank.",
      "Respect scope: a memory from another app or user is 0.",
      "A query with no relevant memory in the pool is a legitimate result; mark it so.",
    ],
  },
  queries: sample.map((c) => ({
    query: c.query,
    shape: c.shape,
    scope: c.scope,
    pool: c.pool.map((id) => ({ id, text: String(live.get(id)?.memory ?? "").slice(0, 1200) })),
    rankings: c.rankings,
    grades: {},
  })),
};

writeFileSync(OUT, JSON.stringify(out, null, 2));
console.log(`\nwrote ${OUT} (${out.queries.length} queries, ${out.queries.reduce((a, q) => a + q.pool.length, 0)} judgments to make)`);
